' Developer Express Code Central Example:
' How to determine the page number of a clicked PDF page
' 
' This example demonstrates how to identify a PDF page in the document by using
' the GetDocumentPosition method of the PdfViewer
' (https://documentation.devexpress.com/#WindowsForms/CustomDocument15216).
' 
' You can find sample updates and versions for different programming languages here:
' http://www.devexpress.com/example=T121897
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Namespace PageHitTest.Properties

    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")>
    Friend NotInheritable Partial Class Settings
        Inherits Global.System.Configuration.ApplicationSettingsBase

        Private Shared defaultInstance As PageHitTest.Properties.Settings = CType((Global.System.Configuration.ApplicationSettingsBase.Synchronized(New PageHitTest.Properties.Settings())), PageHitTest.Properties.Settings)

        Public Shared ReadOnly Property [Default] As Settings
            Get
                Return PageHitTest.Properties.Settings.defaultInstance
            End Get
        End Property
    End Class
End Namespace
